config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events, except: :edit
  get '/', to: 'events#index', as: :root
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  enum event_type: {
    creator_folder: 'creator_folder',
    uploader_file: 'uploader_file',
    unzipper: 'unzipper',
    zipper: 'zipper',
    tree_to_file: 'tree_to_file',
    rename_folder: 'rename_folder',
    converter_html_to_pdf: 'converter_html_to_pdf',
    delete_folder: 'delete_folder'
  }

  validates :name, :event_type, :param1, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.where(executed_at: nil)
  end

  def create
    @event = Event.new(permitted_params)

    if @event.save
      EventsJob.set(wait: rand(5..15).seconds).perform_later(@event)

      redirect_to events_path
    else
      render :new
    end
  end

  def new
    @event = Event.new
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private

  def permitted_params
    params.require(:event).permit(:name, :event_type, :param1, :param2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/views/events/_event.html.slim
tr
  td=event.name
  td=event.param1
  td=event.param2
  td= link_to 'Удалить', event_path(event.id), data: { confirm: 'Удалить?' }, method: :delete

app/views/events/index.html.slim
.actions.col-sm-3
  = link_to 'Создать событие', new_event_path

table.table.table-bordered.col-sm-6
  thead
    tr
      th
        | Название события
      th
        | Первый параметр
      th
        | Второй параметр
      th
        | Второй параметр
  tbody
    = render partial: 'event', collection: @events

app/views/events/new.html.slim
h4 Создание события
= form_with(model: @event, method: :post, local: true, class: :with_validated) do |form|
  = form_group_for(form, :name, label: false) do
    = form.text_field :name, placeholder: 'Название', class: 'form-control'
  = form_group_for(form, :event_type, label: false) do
    = form.select :event_type, Event.event_types.to_a, class: 'form-control'
  = form_group_for(form, :param1, label: false) do
    = form.text_field :param1, placeholder: 'Первый аргумент', class: 'form-control'
  .form-group
    = form.text_field :param2, placeholder: 'Второй', class: 'form-control'
  = form.button type: :submit, class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HgTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>